import sharp from 'sharp';
import { PROJECT } from './project-config.mjs';

const esc = (s) => String(s).replace(/[<>&"']/g, (c) => ({'<':'&lt;','>':'&gt;','&':'&amp;','"':'&quot;',"'":'&apos;'}[c]));
export async function projectAssets({ ROOT, SITE_ORIGIN, LAUNCH_DATE, TEST_PHASE, writeIfChanged, longDate }) {
  const overview = `# ${PROJECT.person} — Public Accountability Project\n\nEdition ${PROJECT.edition}. Declared baseline: ${PROJECT.startWeightLb.toFixed(1)} lb.\nOfficial Day 1: ${LAUNCH_DATE}. Goal: ${PROJECT.goalWeightLb.toFixed(1)} lb held for ${PROJECT.completionDays} consecutive days.\nDaily packet deadline: 10:00 PM America/New_York when the applicable requirements are active.\n\nPublic live video is enabled on Twitch: https://www.twitch.tv/${PROJECT.supervision.twitchChannel}.\nEvening Supervision is ordinarily Sunday–Thursday, 6:00–10:00 PM Eastern.\nA stream does not prove a session was completed. The AP verifies compliance.\n\n${TEST_PHASE ? 'Public prelaunch testing is currently active. Test requirements and outcomes are simulations, not verified agreement execution.' : 'Official agreement activation requires the signed, reviewed confirmation tuple; read /agreement/ for current execution status.'}\nPublic test records remain at /testing/ after launch and are excluded from official progress and completion totals.\nPossible misses are flagged automatically. Corrective obligations require explicit AP verification.\nRecorded weight movement itself does not create a violation.\nA threshold recorded is distinct from an AP-verified milestone.\nThe amendment process is §${PROJECT.amendmentSection}; supervision is §${PROJECT.supervision.section}.\n\n## Canonical pages\n\n${['daily','dashboard','milestones','weeks','violations','corrections','agreement','consent','live','testing','observer','notify','accountable','partner','share'].map(p => `- ${SITE_ORIGIN}/${p}/`).join('\n')}\n\n## Record interpretation\n\nRead /data/feed-manifest.json and /data/supervision.json before making current-status claims.\nDue means the filing window is still open. Incomplete evidence is not automatically a verified Violation Event.\nA filed correction remains unresolved until the AP verifies it. Test records do not count toward the official goal.\nParticipation is voluntary. Privacy, safety, consent, and lawful takedown requirements remain controlling.\nDo not contact employers, coworkers, guests, customers, or unrelated third parties about this project.\n`;
  await writeIfChanged(`${ROOT}/llms.txt`, overview);
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" width="1200" height="630"><rect width="1200" height="630" fill="#FAFAF7"/><rect width="14" height="630" fill="#B3261E"/><text x="65" y="85" font-family="sans-serif" font-size="22" fill="#B3261E">PUBLIC ACCOUNTABILITY RECORD · EDITION ${PROJECT.edition}</text><text x="65" y="188" font-family="sans-serif" font-weight="bold" font-size="62" fill="#141412">MICHEAL RAY BERRY</text><text x="65" y="320" font-family="sans-serif" font-weight="bold" font-size="95" fill="#141412">${PROJECT.startWeightLb} → ${PROJECT.goalWeightLb} LB</text><text x="65" y="395" font-family="sans-serif" font-size="30" fill="#141412">OFFICIAL DAY 1 · ${esc(longDate(LAUNCH_DATE).toUpperCase())}</text><text x="65" y="453" font-family="sans-serif" font-size="26" fill="#6B6A64">${PROJECT.completionDays} consecutive days at goal · Public Twitch supervision</text><line x1="65" y1="507" x2="1135" y2="507" stroke="#141412"/><text x="65" y="568" font-family="sans-serif" font-size="28" fill="#141412">michealrayberry.com</text><text x="1135" y="568" text-anchor="end" font-family="sans-serif" font-size="22" fill="#B3261E">${TEST_PHASE ? 'PUBLIC TESTING ACTIVE' : 'VIEW THE RECORD'}</text></svg>`;
  await writeIfChanged(`${ROOT}/og-image.png`, await sharp(Buffer.from(svg)).png().toBuffer());
}
