/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as AgreementRouteImport } from './routes/agreement'
import { Route as CornerTimeRouteImport } from './routes/corner-time'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as HomeRouteImport } from './routes/home'
import { Route as LoginRouteImport } from './routes/login'
import { Route as MilestonesRouteImport } from './routes/milestones'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as PenaltiesRouteImport } from './routes/penalties'
import { Route as UniformRouteImport } from './routes/uniform'
import { Route as UpdatesRouteImport } from './routes/updates'
import { Route as AssistantIndexRouteImport } from './routes/assistant/index'
import { Route as DailyIndexRouteImport } from './routes/daily/index'
import { Route as DailySlugRouteImport } from './routes/daily/$slug'
import { Route as PositionsIndexRouteImport } from './routes/positions/index'
import { Route as ViolationsIdRouteImport } from './routes/violations/$id'
import { Route as WeeksIndexRouteImport } from './routes/weeks/index'
import { Route as ApiAuthSplatRouteImport } from './routes/api/auth/$'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const AgreementRoute = AgreementRouteImport.update({
  id: '/agreement',
  path: '/agreement',
  getParentRoute: () => rootRouteImport,
} as any)
const CornerTimeRoute = CornerTimeRouteImport.update({
  id: '/corner-time',
  path: '/corner-time',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeRoute = HomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const MilestonesRoute = MilestonesRouteImport.update({
  id: '/milestones',
  path: '/milestones',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const PenaltiesRoute = PenaltiesRouteImport.update({
  id: '/penalties',
  path: '/penalties',
  getParentRoute: () => rootRouteImport,
} as any)
const UniformRoute = UniformRouteImport.update({
  id: '/uniform',
  path: '/uniform',
  getParentRoute: () => rootRouteImport,
} as any)
const UpdatesRoute = UpdatesRouteImport.update({
  id: '/updates',
  path: '/updates',
  getParentRoute: () => rootRouteImport,
} as any)
const AssistantIndexRoute = AssistantIndexRouteImport.update({
  id: '/assistant/',
  path: '/assistant/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailyIndexRoute = DailyIndexRouteImport.update({
  id: '/daily/',
  path: '/daily/',
  getParentRoute: () => rootRouteImport,
} as any)
const DailySlugRoute = DailySlugRouteImport.update({
  id: '/daily/$slug',
  path: '/daily/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const PositionsIndexRoute = PositionsIndexRouteImport.update({
  id: '/positions/',
  path: '/positions/',
  getParentRoute: () => rootRouteImport,
} as any)
const ViolationsIdRoute = ViolationsIdRouteImport.update({
  id: '/violations/$id',
  path: '/violations/$id',
  getParentRoute: () => rootRouteImport,
} as any)
const WeeksIndexRoute = WeeksIndexRouteImport.update({
  id: '/weeks/',
  path: '/weeks/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSplatRoute = ApiAuthSplatRouteImport.update({
  id: '/api/auth/$',
  path: '/api/auth/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agreement': typeof AgreementRoute
  '/corner-time': typeof CornerTimeRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/milestones': typeof MilestonesRoute
  '/partner': typeof PartnerRoute
  '/penalties': typeof PenaltiesRoute
  '/uniform': typeof UniformRoute
  '/updates': typeof UpdatesRoute
  '/daily/$slug': typeof DailySlugRoute
  '/violations/$id': typeof ViolationsIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/daily/': typeof DailyIndexRoute
  '/positions/': typeof PositionsIndexRoute
  '/weeks/': typeof WeeksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agreement': typeof AgreementRoute
  '/corner-time': typeof CornerTimeRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/milestones': typeof MilestonesRoute
  '/partner': typeof PartnerRoute
  '/penalties': typeof PenaltiesRoute
  '/uniform': typeof UniformRoute
  '/updates': typeof UpdatesRoute
  '/daily/$slug': typeof DailySlugRoute
  '/violations/$id': typeof ViolationsIdRoute
  '/assistant': typeof AssistantIndexRoute
  '/daily': typeof DailyIndexRoute
  '/positions': typeof PositionsIndexRoute
  '/weeks': typeof WeeksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/agreement': typeof AgreementRoute
  '/corner-time': typeof CornerTimeRoute
  '/dashboard': typeof DashboardRoute
  '/home': typeof HomeRoute
  '/login': typeof LoginRoute
  '/milestones': typeof MilestonesRoute
  '/partner': typeof PartnerRoute
  '/penalties': typeof PenaltiesRoute
  '/uniform': typeof UniformRoute
  '/updates': typeof UpdatesRoute
  '/daily/$slug': typeof DailySlugRoute
  '/violations/$id': typeof ViolationsIdRoute
  '/assistant/': typeof AssistantIndexRoute
  '/daily/': typeof DailyIndexRoute
  '/positions/': typeof PositionsIndexRoute
  '/weeks/': typeof WeeksIndexRoute
  '/api/auth/$': typeof ApiAuthSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/agreement'
    | '/corner-time'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/milestones'
    | '/partner'
    | '/penalties'
    | '/uniform'
    | '/updates'
    | '/daily/$slug'
    | '/violations/$id'
    | '/assistant/'
    | '/daily/'
    | '/positions/'
    | '/weeks/'
    | '/api/auth/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/agreement'
    | '/corner-time'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/milestones'
    | '/partner'
    | '/penalties'
    | '/uniform'
    | '/updates'
    | '/daily/$slug'
    | '/violations/$id'
    | '/assistant'
    | '/daily'
    | '/positions'
    | '/weeks'
    | '/api/auth/$'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/agreement'
    | '/corner-time'
    | '/dashboard'
    | '/home'
    | '/login'
    | '/milestones'
    | '/partner'
    | '/penalties'
    | '/uniform'
    | '/updates'
    | '/daily/$slug'
    | '/violations/$id'
    | '/assistant/'
    | '/daily/'
    | '/positions/'
    | '/weeks/'
    | '/api/auth/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AgreementRoute: typeof AgreementRoute
  CornerTimeRoute: typeof CornerTimeRoute
  DashboardRoute: typeof DashboardRoute
  HomeRoute: typeof HomeRoute
  LoginRoute: typeof LoginRoute
  MilestonesRoute: typeof MilestonesRoute
  PartnerRoute: typeof PartnerRoute
  PenaltiesRoute: typeof PenaltiesRoute
  UniformRoute: typeof UniformRoute
  UpdatesRoute: typeof UpdatesRoute
  DailySlugRoute: typeof DailySlugRoute
  ViolationsIdRoute: typeof ViolationsIdRoute
  AssistantIndexRoute: typeof AssistantIndexRoute
  DailyIndexRoute: typeof DailyIndexRoute
  PositionsIndexRoute: typeof PositionsIndexRoute
  WeeksIndexRoute: typeof WeeksIndexRoute
  ApiAuthSplatRoute: typeof ApiAuthSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agreement': {
      id: '/agreement'
      path: '/agreement'
      fullPath: '/agreement'
      preLoaderRoute: typeof AgreementRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/corner-time': {
      id: '/corner-time'
      path: '/corner-time'
      fullPath: '/corner-time'
      preLoaderRoute: typeof CornerTimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/home': {
      id: '/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof HomeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/milestones': {
      id: '/milestones'
      path: '/milestones'
      fullPath: '/milestones'
      preLoaderRoute: typeof MilestonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/penalties': {
      id: '/penalties'
      path: '/penalties'
      fullPath: '/penalties'
      preLoaderRoute: typeof PenaltiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/uniform': {
      id: '/uniform'
      path: '/uniform'
      fullPath: '/uniform'
      preLoaderRoute: typeof UniformRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/updates': {
      id: '/updates'
      path: '/updates'
      fullPath: '/updates'
      preLoaderRoute: typeof UpdatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assistant/': {
      id: '/assistant/'
      path: '/assistant'
      fullPath: '/assistant/'
      preLoaderRoute: typeof AssistantIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/': {
      id: '/daily/'
      path: '/daily'
      fullPath: '/daily/'
      preLoaderRoute: typeof DailyIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/daily/$slug': {
      id: '/daily/$slug'
      path: '/daily/$slug'
      fullPath: '/daily/$slug'
      preLoaderRoute: typeof DailySlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/positions/': {
      id: '/positions/'
      path: '/positions'
      fullPath: '/positions/'
      preLoaderRoute: typeof PositionsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/violations/$id': {
      id: '/violations/$id'
      path: '/violations/$id'
      fullPath: '/violations/$id'
      preLoaderRoute: typeof ViolationsIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/weeks/': {
      id: '/weeks/'
      path: '/weeks'
      fullPath: '/weeks/'
      preLoaderRoute: typeof WeeksIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/$': {
      id: '/api/auth/$'
      path: '/api/auth/$'
      fullPath: '/api/auth/$'
      preLoaderRoute: typeof ApiAuthSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AgreementRoute: AgreementRoute,
  CornerTimeRoute: CornerTimeRoute,
  DashboardRoute: DashboardRoute,
  HomeRoute: HomeRoute,
  LoginRoute: LoginRoute,
  MilestonesRoute: MilestonesRoute,
  PartnerRoute: PartnerRoute,
  PenaltiesRoute: PenaltiesRoute,
  UniformRoute: UniformRoute,
  UpdatesRoute: UpdatesRoute,
  DailySlugRoute: DailySlugRoute,
  ViolationsIdRoute: ViolationsIdRoute,
  AssistantIndexRoute: AssistantIndexRoute,
  DailyIndexRoute: DailyIndexRoute,
  PositionsIndexRoute: PositionsIndexRoute,
  WeeksIndexRoute: WeeksIndexRoute,
  ApiAuthSplatRoute: ApiAuthSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
